# Generated by Django 4.1.3 on 2023-01-03 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_author_book_genre_bookinstance_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
