# Generated by Django 4.1.3 on 2023-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
