# Generated by Django 4.1.3 on 2023-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_bookinstance_borrow_date_bookinstance_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='last_borrowed',
            field=models.DateField(null=True),
        ),
    ]
