# Generated by Django 4.1.3 on 2023-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_bookinstance_last_borrowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingtransaction',
            old_name='student',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='incomingtransaction',
            old_name='date',
            new_name='date_returned',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='student',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='date',
            new_name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='last_borrowed',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='return_date',
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
