# Generated by Django 4.1.3 on 2023-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
