# Generated by Django 4.1.3 on 2023-01-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_bookinstance_location_alter_student_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
