# Generated by Django 4.1.3 on 2023-01-24 04:59

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_customuser_is_active_alter_student_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(default=system.models.generate_school_id, max_length=15, unique=True),
        ),
    ]
