# Generated by Django 4.1.3 on 2023-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_student_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
