# Generated by Django 4.1.3 on 2023-01-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_student_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
