# Generated by Django 4.1.3 on 2023-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'On loan'), (1, 'Available')], default=1, max_length=1),
        ),
    ]
