# Generated by Django 4.1.3 on 2023-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.IntegerField(choices=[(0, 'On loan'), (1, 'Available')], default=1),
        ),
    ]
