# Generated by Django 4.1.3 on 2023-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='book_thumbnails/'),
        ),
    ]
