# Generated by Django 4.1.3 on 2023-02-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_alter_reservations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservations',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student', unique=True),
        ),
    ]
