# Generated by Django 4.1.3 on 2023-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_reservations_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date_reserved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
