# Generated by Django 4.1.3 on 2023-02-12 11:37

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_reservations_date_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='expiry_date',
            field=models.DateTimeField(db_index=True, default=system.models.reservation_expiry_date),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date_reserved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
