# Generated by Django 4.1.3 on 2023-05-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_alter_book_isbn_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
