# Generated by Django 4.1.3 on 2023-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(0, 'Book'), (1, 'Thesis materials')], default=0),
        ),
    ]
