# Generated by Django 4.1.3 on 2023-05-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.book',),
        ),
    ]
