# Generated by Django 4.1.3 on 2023-07-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_thesisbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='incoming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.incomingtransaction'),
        ),
    ]
