# Generated by Django 4.1.3 on 2023-07-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_outgoingtransaction_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='incoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.incomingtransaction'),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='return_date',
            field=models.DateField(null=True, verbose_name='Due date'),
        ),
    ]
